import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the monthly timesheet from saved daily reports", async () => {
  const api = await readFile(new URL("../app/api/timesheet/route.ts", import.meta.url), "utf8");
  const view = await readFile(new URL("../app/TimesheetView.tsx", import.meta.url), "utf8");
  const clipboard = await readFile(new URL("../app/useTimesheetClipboard.ts", import.meta.url), "utf8");
  const columnFilter = await readFile(new URL("../app/TimesheetColumnFilter.tsx", import.meta.url), "utf8");
  const xlsx = await readFile(new URL("../app/placementXlsx.ts", import.meta.url), "utf8");
  const app = await readFile(new URL("../app/PersonnelApp.tsx", import.meta.url), "utf8");
  const roles = await readFile(new URL("../app/roles.ts", import.meta.url), "utf8");
  const migration = await readFile(new URL("../drizzle-postgres/0007_timesheet_marks.sql", import.meta.url), "utf8");
  const cleanupMigration = await readFile(new URL("../drizzle-postgres/0008_position_catalog_cleanup.sql", import.meta.url), "utf8");
  const dockerfile = await readFile(new URL("../Dockerfile", import.meta.url), "utf8");
  const startup = await readFile(new URL("../scripts/start-production.mjs", import.meta.url), "utf8");
  const migrationRunner = await readFile(new URL("../scripts/apply-postgres-migrations.mjs", import.meta.url), "utf8");
  const yandexPostgres = await readFile(new URL("../scripts/yandex-postgres.mjs", import.meta.url), "utf8");

  assert.match(api, /getAuthUser\(request\)/);
  assert.match(api, /!canAccessTimesheets\(authUser\.role\)/);
  assert.match(api, /Табели доступны только инженеру и супер-администратору/);
  assert.match(api, /authUser\.role === "foreman"/);
  assert.match(api, /pe\.work_date >= \? AND pe\.work_date < \?/);
  assert.match(api, /SUM\(pe\.hours\)::int AS hours/);
  assert.match(api, /GROUP BY pe\.employee_id, pe\.work_date/);
  assert.match(api, /pe\.deleted_at IS NULL/);
  assert.match(api, /CREATE TABLE IF NOT EXISTS timesheet_marks/);
  assert.match(api, /TIMESHEET_CODES/);
  assert.match(api, /assertSameOrigin\(request\)/);
  assert.match(api, /authUser\.role === "foreman"/);
  assert.match(api, /ON CONFLICT \(site_id, employee_id, work_date\) DO UPDATE/);
  assert.match(api, /hours BETWEEN 1 AND 10/);
  assert.match(api, /marks: marksResult\.results/);
  assert.doesNotMatch(api, /availability_status = 'on_site'/);

  assert.match(migration, /CREATE TABLE IF NOT EXISTS "timesheet_marks"/);
  assert.match(migration, /ALTER COLUMN "work_date" TYPE date/);
  assert.match(migration, /timesheet_hours_range/);
  assert.match(migration, /timesheet_value_required/);
  assert.match(migration, /idx_timesheet_marks_unique_day/);

  assert.match(cleanupMigration, /UPDATE "position_catalog"/);
  assert.match(cleanupMigration, /SET "active" = 0/);
  assert.doesNotMatch(cleanupMigration, /UPDATE "employees"/);
  assert.match(cleanupMigration, /'ОПР', 'УСР', 'Стропальщик'/);

  assert.match(dockerfile, /CMD \["node", "scripts\/start-production\.mjs"\]/);
  assert.match(dockerfile, /node_modules\/drizzle-orm/);
  assert.match(startup, /apply-postgres-migrations\.mjs/);
  assert.match(startup, /server\.js/);
  assert.match(migrationRunner, /pg_advisory_lock/);
  assert.match(migrationRunner, /pg_advisory_unlock/);
  assert.match(yandexPostgres, /rc1b-p176vla5mhlldu1a\.mdb\.yandexcloud\.net/);
  assert.match(yandexPostgres, /cloud-system-yums-personnel/);

  assert.match(view, /Табель учёта рабочего времени/);
  assert.match(view, /Выбрать месяц, сейчас/);
  assert.match(view, /Итоги за месяц/);
  assert.match(view, /Итого по дням/);
  assert.match(view, /Вернуть значение из отчёта/);
  assert.match(view, /TimesheetFilterableHeading/);
  assert.match(view, /label="Тип"/);
  assert.match(view, /label="Сотрудник"/);
  assert.match(view, /label="Должность"/);
  assert.match(view, /dayFilterOptions/);
  assert.match(view, /Есть расхождение/);
  assert.match(view, /timesheet-header-filter-reset/);
  assert.match(view, /const mismatch = isMismatch\(employee, entry, mark\)/);
  assert.match(view, /mismatch \? "mismatch" : ""/);
  assert.doesNotMatch(view, /Сверка с ежедневными отчётами/);
  assert.doesNotMatch(view, /По мастерам/);
  assert.doesNotMatch(view, /По зонам/);
  assert.match(view, /Табельные коды/);
  assert.doesNotMatch(view, /timesheet-filter-panel/);
  assert.doesNotMatch(view, /timesheet-search/);
  assert.doesNotMatch(view, /timesheet-overview-expanded/);
  assert.match(view, /Вернуть значение из отчёта/);
  assert.match(view, /TIMESHEET_CODES/);
  assert.match(view, /openInlineEditor/);
  assert.match(view, /timesheet-cell-inline-editor/);
  assert.match(view, /aria-invalid=\{Boolean\(inlineEditor\.error\)\}/);
  assert.match(view, /void saveInlineEditor\(\)/);
  assert.match(view, /TIMESHEET_MARK_OPTIONS/);
  assert.match(view, /timesheet-cell-dropdown/);
  assert.match(view, /personnel-timesheet-cell-dropdown/);
  assert.match(view, /editor\?\.employeeId === employeeId && editor\.workDate === workDate/);
  assert.match(view, /aria-expanded=\{editor\?\.employeeId === employee\.id && editor\.workDate === workDate\}/);
  assert.match(view, /isActiveCell && <button/);
  assert.match(view, /Выбрать значение из списка/);
  assert.match(view, /onType: \(rowIndex, columnIndex, _anchor, value\)/);
  assert.match(view, /openInlineEditor\(employee\.id, dateForDay\(month, day\), rowIndex, columnIndex, value\)/);
  assert.match(view, /TimesheetMarkList/);
  assert.match(view, /custom-select-options timesheet-mark-options/);
  assert.match(view, /custom-select-option/);
  assert.match(view, /Недопустимое значение/);
  assert.match(view, /closeEditorAndRestoreGridFocus/);
  assert.match(view, /clipboardShellRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(view, /personnel-timesheet-summary/);
  assert.match(view, /exportTimesheet/);
  assert.match(view, /createPersonnelTimesheetXlsx/);
  assert.match(view, /Табель_рабочих_/);
  assert.match(view, /timesheet-export-button/);
  assert.match(view, /TimesheetMonthPicker/);
  assert.match(view, /timesheet-month-popover/);
  assert.match(view, /Выбор месяца табеля/);
  assert.doesNotMatch(view, /type="month"/);
  assert.match(view, /canDelete:/);
  assert.match(view, /marksByCell\.has/);
  assert.match(view, /onDelete: pasteTimesheetCells/);
  assert.match(clipboard, /event\.key !== "Delete" && event\.key !== "Backspace"/);
  assert.match(clipboard, /ArrowLeft/);
  assert.match(clipboard, /ArrowRight/);
  assert.match(clipboard, /ArrowUp/);
  assert.match(clipboard, /ArrowDown/);
  assert.match(clipboard, /event\.shiftKey/);
  assert.match(clipboard, /scrollIntoView\(\{ block: "nearest", inline: "nearest" \}\)/);
  assert.match(clipboard, /scrollCellIntoVisibleArea/);
  assert.match(clipboard, /lastHeaderCell/);
  assert.match(clipboard, /footerCell/);
  assert.match(clipboard, /shell\.scrollBy\(\{ top: verticalOffset, left: horizontalOffset \}\)/);
  assert.match(clipboard, /event\.key === "Enter" \|\| event\.key === "F2"/);
  assert.match(clipboard, /onActivate\(current\.rowIndex, current\.columnIndex, anchor\)/);
  assert.match(clipboard, /event\.key\.length === 1/);
  assert.match(clipboard, /onType\(current\.rowIndex, current\.columnIndex, anchor, event\.key\)/);
  assert.match(view, /onActivate: \(rowIndex, columnIndex\)/);
  assert.match(view, /Стрелки перемещают выбранную ячейку/);
  assert.match(clipboard, /Удалено ручных значений/);
  assert.match(clipboard, /value: ""/);
  assert.match(clipboard, /event\.ctrlKey \|\| event\.metaKey/);
  assert.match(clipboard, /undoStack/);
  assert.match(clipboard, /rememberUndo/);
  assert.match(view, /getUndoNote/);

  assert.match(columnFilter, /timesheet-header-filter/);
  assert.match(columnFilter, /"Фильтр и сортировка" : "Фильтр"/);
  assert.match(columnFilter, /timesheet-filter-popover/);
  assert.match(columnFilter, /createPortal/);
  assert.match(columnFilter, /Найти значение/);
  assert.match(columnFilter, /Выбрать все/);
  assert.match(columnFilter, /Применить/);
  assert.doesNotMatch(columnFilter, /<select/);

  assert.match(xlsx, /export function createPersonnelTimesheetXlsx/);
  assert.match(xlsx, /Фамилия, имя, отчество/);
  assert.match(xlsx, /Примечание к должности/);
  assert.match(xlsx, /"РАСТ"/);
  assert.match(xlsx, /"Проверка"/);
  assert.match(xlsx, /Часы по табелю/);
  assert.match(xlsx, /autoFilter ref="B2:F\$\{totalRowNumber\}"/);
  assert.doesNotMatch(xlsx, /formulaStringCell/);
  assert.match(xlsx, /SUM\(G\$\{rowNumber\}:AK\$\{rowNumber\}\)/);
  assert.doesNotMatch(xlsx, /const weekdayCells/);
  assert.match(xlsx, /sort\(\(left, right\) => cellXmlColumnIndex\(left\) - cellXmlColumnIndex\(right\)\)/);
  assert.match(xlsx, /workbookFiles\(worksheet, undefined, "Табель"\)/);

  assert.match(app, /view === "timesheet"/);
  assert.match(app, /<TimesheetView/);
  assert.match(app, /mayAccessTimesheets && <div className="nav-group">/);
  assert.match(app, /mayAccessTimesheets && view === "timesheet"/);
  assert.match(app, /mayAccessTimesheets && view === "equipmentTimesheet"/);
  assert.match(app, /timesheet-navigation/);
  assert.match(app, />Табели</);
  assert.match(app, /aria-label="Табель рабочих"/);
  assert.match(app, /aria-label="Табель техники"/);
  assert.match(roles, /canAccessTimesheets/);
  assert.match(roles, /role === "engineer" \|\| role === "superadmin"/);
});

test("allows future personnel planning and warns the daily report about timesheet conflicts", async () => {
  const timesheetApi = await readFile(new URL("../app/api/timesheet/route.ts", import.meta.url), "utf8");
  const dataApi = await readFile(new URL("../app/api/data/route.ts", import.meta.url), "utf8");
  const timesheetView = await readFile(new URL("../app/TimesheetView.tsx", import.meta.url), "utf8");
  const app = await readFile(new URL("../app/PersonnelApp.tsx", import.meta.url), "utf8");
  const grid = await readFile(new URL("../app/AgDataGrids.tsx", import.meta.url), "utf8");

  assert.doesNotMatch(timesheetApi, /Будущие дни пока нельзя заполнять/);
  assert.doesNotMatch(timesheetView, /workDate > today\) return/);
  assert.match(timesheetView, /<TimesheetMonthPicker value=\{month\} current=\{currentMonth\}/);
  assert.match(timesheetView, /aria-label="Следующий месяц"/);

  assert.match(dataApi, /function reportTimesheetMarksStatement\(siteId: number, workDate: string\)/);
  assert.match(dataApi, /timesheetMarks: timesheetMarks\.results/);
  assert.match(app, /timesheetMarks=\{data\?\.timesheetMarks \?\? \[\]\}/);
  assert.match(grid, /timesheet-conflict-row/);
  assert.match(grid, /Несовпадение с табелем/);
  assert.match(grid, /Табель: \$\{mark\.hours\} ч\. · отчёт: \$\{reportHours\} ч\./);
});
