CREATE TABLE IF NOT EXISTS "audit_events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_user_id" integer REFERENCES "app_users"("id") ON DELETE SET NULL,
  "actor_name" text NOT NULL,
  "actor_role" text NOT NULL,
  "category" text NOT NULL,
  "action_key" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text NOT NULL DEFAULT '',
  "site_id" integer REFERENCES "sites"("id") ON DELETE SET NULL,
  "site_name" text NOT NULL DEFAULT '',
  "summary" text NOT NULL,
  "before_data" jsonb,
  "after_data" jsonb,
  "request_path" text NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_events_created" ON "audit_events" ("created_at" DESC, "id" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_events_actor" ON "audit_events" ("actor_user_id", "created_at" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_events_category" ON "audit_events" ("category", "created_at" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_events_site" ON "audit_events" ("site_id", "created_at" DESC);
