import { getDatabase } from "../db/client";
import { getAuthUser, type AuthUser } from "./auth";

export type AuditCategory = "reports" | "timesheets" | "directories" | "access" | "equipment" | "integration" | "account";

type AuditDraft = {
  actor: AuthUser;
  category: AuditCategory;
  actionKey: string;
  entityType: string;
  entityId: string;
  siteId: number | null;
  siteName: string;
  summary: string;
  beforeData: unknown;
  requestedData: unknown;
  requestPath: string;
};

let auditSchemaPromise: Promise<void> | null = null;

export async function ensureAuditSchema() {
  if (!auditSchemaPromise) {
    const db = getDatabase();
    auditSchemaPromise = db.batch([
      db.prepare(`CREATE TABLE IF NOT EXISTS audit_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
        actor_name TEXT NOT NULL,
        actor_role TEXT NOT NULL,
        category TEXT NOT NULL,
        action_key TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL DEFAULT '',
        site_id INTEGER REFERENCES sites(id) ON DELETE SET NULL,
        site_name TEXT NOT NULL DEFAULT '',
        summary TEXT NOT NULL,
        before_data JSONB,
        after_data JSONB,
        request_path TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`),
      db.prepare("CREATE INDEX IF NOT EXISTS idx_audit_events_created ON audit_events(created_at DESC, id DESC)"),
      db.prepare("CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON audit_events(actor_user_id, created_at DESC)"),
      db.prepare("CREATE INDEX IF NOT EXISTS idx_audit_events_category ON audit_events(category, created_at DESC)"),
      db.prepare("CREATE INDEX IF NOT EXISTS idx_audit_events_site ON audit_events(site_id, created_at DESC)"),
    ]).then(() => undefined).catch((error) => {
      auditSchemaPromise = null;
      throw error;
    });
  }
  return auditSchemaPromise;
}

function positiveInteger(value: unknown) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

function sensitiveKey(key: string) {
  return /password|token|secret|webhook|invitationurl|cookie/i.test(key);
}

function safeAuditValue(value: unknown, key = "", depth = 0): unknown {
  if (sensitiveKey(key)) return undefined;
  if (value === null || typeof value === "number" || typeof value === "boolean") return value;
  if (typeof value === "string") return value.slice(0, 1_000);
  if (depth >= 5) return "[вложенные данные скрыты]";
  if (Array.isArray(value)) {
    const items = value.slice(0, 200).map((item) => safeAuditValue(item, key, depth + 1));
    return value.length > 200 ? { total: value.length, items, truncated: true } : items;
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value)
      .filter(([entryKey]) => !sensitiveKey(entryKey))
      .map(([entryKey, entryValue]) => [entryKey, safeAuditValue(entryValue, entryKey, depth + 1)]));
  }
  return String(value ?? "").slice(0, 1_000);
}

async function requestPayload(request: Request) {
  if (!request.headers.get("content-type")?.includes("application/json")) return {} as Record<string, unknown>;
  try {
    const value = await request.json();
    return value && typeof value === "object" ? value as Record<string, unknown> : {};
  } catch {
    return {} as Record<string, unknown>;
  }
}

function firstWorkDate(payload: Record<string, unknown>) {
  if (typeof payload.workDate === "string") return payload.workDate;
  for (const key of ["submitOwnReport", "finalizeReport"]) {
    const nested = payload[key];
    if (nested && typeof nested === "object" && typeof (nested as Record<string, unknown>).workDate === "string") return String((nested as Record<string, unknown>).workDate);
  }
  const rows = Array.isArray(payload.entries) ? payload.entries : Array.isArray(payload.creates) ? payload.creates : Array.isArray(payload.updates) ? payload.updates : [];
  const first = rows[0];
  return first && typeof first === "object" && typeof (first as Record<string, unknown>).workDate === "string"
    ? String((first as Record<string, unknown>).workDate)
    : "";
}

function firstSiteId(payload: Record<string, unknown>, url: URL) {
  const direct = positiveInteger(payload.siteId) ?? positiveInteger(url.searchParams.get("siteId"));
  if (direct) return direct;
  for (const key of ["submitOwnReport", "finalizeReport"]) {
    const nested = payload[key];
    if (nested && typeof nested === "object") {
      const siteId = positiveInteger((nested as Record<string, unknown>).siteId);
      if (siteId) return siteId;
    }
  }
  const collections = [payload.entries, payload.creates, payload.updates];
  for (const collection of collections) {
    if (!Array.isArray(collection) || !collection[0] || typeof collection[0] !== "object") continue;
    const siteId = positiveInteger((collection[0] as Record<string, unknown>).siteId);
    if (siteId) return siteId;
  }
  return null;
}

function actionDescription(path: string, method: string, payload: Record<string, unknown>, url: URL) {
  const action = typeof payload.action === "string" ? payload.action : "";
  const workDate = firstWorkDate(payload);
  const id = positiveInteger(payload.id) ?? positiveInteger(payload.employeeId) ?? positiveInteger(payload.equipmentId) ?? positiveInteger(url.searchParams.get("id"));
  if (action === "inspect-bitrix24") return null;

  if (path === "/api/timesheet") {
    const value = String(payload.value ?? "").trim();
    return {
      category: "timesheets" as const, actionKey: value ? "personnel_timesheet.set" : "personnel_timesheet.delete",
      entityType: "employee_timesheet", entityId: String(payload.employeeId ?? ""),
      summary: value ? `Установил отметку «${value}» в табеле рабочих${workDate ? ` за ${workDate}` : ""}` : `Удалил ручную отметку из табеля рабочих${workDate ? ` за ${workDate}` : ""}`,
    };
  }
  if (path === "/api/equipment") {
    const descriptions: Record<string, [AuditCategory, string, string]> = {
      "submit-daily-report": ["reports", "equipment_report.submit", `Сдал отчёт техники${workDate ? ` за ${workDate}` : ""}`],
      "save-entry": ["reports", id ? "equipment_report.update" : "equipment_report.create", `${id ? "Изменил" : "Добавил"} строку отчёта техники${workDate ? ` за ${workDate}` : ""}`],
      "delete-entry": ["reports", "equipment_report.delete", "Удалил строку отчёта техники"],
      "import-entries": ["reports", "equipment_report.import", "Импортировал строки отчёта техники"],
      "save-timesheet-mark": ["timesheets", Number(payload.productiveHours ?? 0) || Number(payload.downtimeHours ?? 0) || String(payload.note ?? "").trim() ? "equipment_timesheet.set" : "equipment_timesheet.delete", `Изменил табель техники${workDate ? ` за ${workDate}` : ""}`],
      "assign-unit-project": ["equipment", "equipment.assign", "Назначил технику на проект"],
      "remove-unit-project": ["equipment", "equipment.unassign", "Убрал технику из проекта"],
      "save-unit": ["equipment", id ? "equipment.update" : "equipment.create", `${id ? "Изменил" : "Добавил"} единицу техники`],
      "delete-unit": ["equipment", "equipment.delete", "Удалил единицу техники"],
      "import-units": ["equipment", "equipment.import", "Импортировал реестр техники"],
    };
    const description = descriptions[action];
    if (!description) return null;
    return { category: description[0], actionKey: description[1], entityType: action.includes("timesheet") ? "equipment_timesheet" : action.includes("entry") || action === "submit-daily-report" || action === "import-entries" ? "equipment_report" : "equipment", entityId: String(id ?? ""), summary: description[2] };
  }
  if (path === "/api/auth/password") return { category: "account" as const, actionKey: "account.password", entityType: "user", entityId: "", summary: "Изменил пароль своей учётной записи" };
  if (path === "/api/access-rights") return {
    category: "access" as const,
    actionKey: payload.reset === true ? "access_rights.reset" : "access_rights.update",
    entityType: "user_permissions",
    entityId: String(payload.userId ?? ""),
    summary: payload.reset === true ? "Вернул пользователю права его роли" : "Изменил права доступа пользователя",
  };
  if (path !== "/api/data") return null;

  if (method === "DELETE" && payload.entity) {
    const entity = String(payload.entity);
    const ids = Array.isArray(payload.ids) ? payload.ids : payload.id ? [payload.id] : [];
    const count = ids.length || 1;
    const deleted: Record<string, [AuditCategory, string, string, string]> = {
      employee: ["directories", "employee.delete", `Удалил сотрудников: ${count}`, "employee"],
      "employee-assignment": ["directories", "employee.unassign", "Убрал сотрудника из проекта", "employee"],
      user: ["access", "user.delete", "Удалил пользователя системы", "user"],
      site: ["directories", "project.delete", "Удалил проект", "project"],
      position: ["directories", "position.delete", "Удалил должность", "position"],
      directory: ["directories", "directory.delete", "Удалил значение справочника", "directory"],
    };
    const description = deleted[entity];
    if (description) return { category: description[0], actionKey: description[1], entityType: description[3], entityId: ids.length === 1 ? String(ids[0]) : "", summary: description[2] };
  }

  if (!action) {
    const submitted = payload.submitReport || payload.submitOwnReport || payload.finalizeReport;
    const verb = method === "DELETE" ? "Удалил строки" : submitted ? "Сдал отчёт" : "Сохранил изменения";
    return { category: "reports" as const, actionKey: submitted ? "personnel_report.submit" : method === "DELETE" ? "personnel_report.delete" : "personnel_report.save", entityType: "personnel_report", entityId: String(id ?? ""), summary: `${verb} рабочих${workDate ? ` за ${workDate}` : ""}` };
  }
  const descriptions: Record<string, [AuditCategory, string, string, string]> = {
    "sync-bitrix24": ["integration", "bitrix.sync", "Применил данные из Битрикс24", "employee"],
    "create-user": ["access", "user.create", `Добавил пользователя «${String(payload.fullName ?? "") || "Без имени"}»`, "user"],
    "update-user": ["access", "user.update", `Изменил пользователя «${String(payload.fullName ?? "") || "Без имени"}»`, "user"],
    "create-employee": ["directories", "employee.create", `Добавил сотрудника «${String(payload.fullName ?? "") || "Без имени"}»`, "employee"],
    "update-employee": ["directories", "employee.update", `Изменил сотрудника «${String(payload.fullName ?? "") || "Без имени"}»`, "employee"],
    "import-employees": ["directories", "employee.import", "Импортировал список сотрудников", "employee"],
    "assign-employee-project": ["directories", "employee.assign", "Добавил сотрудника в проект", "employee"],
    "create-position": ["directories", "position.create", `Добавил должность «${String(payload.position ?? "") || "Без названия"}»`, "position"],
    "update-position": ["directories", "position.update", `Изменил должность «${String(payload.position ?? "") || "Без названия"}»`, "position"],
    "import-positions": ["directories", "position.import", "Импортировал список должностей", "position"],
    "create-site": ["directories", "project.create", `Добавил проект «${String(payload.name ?? "") || "Без названия"}»`, "project"],
    "update-site": ["directories", "project.update", `Изменил проект «${String(payload.name ?? "") || "Без названия"}»`, "project"],
    "create-directory": ["directories", "directory.create", `Добавил значение справочника «${String(payload.name ?? "") || "Без названия"}»`, "directory"],
    "update-directory": ["directories", "directory.update", `Изменил значение справочника «${String(payload.name ?? "") || "Без названия"}»`, "directory"],
    "save-directory-items": ["directories", "directory.save", "Сохранил изменения справочника", "directory"],
    "assign-site": ["access", "user.assign", "Изменил проект пользователя", "user"],
  };
  const description = descriptions[action];
  if (!description) return null;
  return { category: description[0], actionKey: description[1], entityType: description[3], entityId: String(id ?? payload.userId ?? payload.positionId ?? payload.siteId ?? payload.directoryId ?? ""), summary: description[2] };
}

async function previousState(path: string, method: string, payload: Record<string, unknown>) {
  const db = getDatabase();
  if (path === "/api/timesheet") {
    const siteId = positiveInteger(payload.siteId);
    const employeeId = positiveInteger(payload.employeeId);
    const workDate = typeof payload.workDate === "string" ? payload.workDate : "";
    if (!siteId || !employeeId || !workDate) return null;
    return db.prepare(`SELECT tm.hours, tm.code, tm.note, tm.created_by AS "updatedBy", e.full_name AS "employeeName"
      FROM employees e LEFT JOIN timesheet_marks tm ON tm.employee_id = e.id AND tm.site_id = ? AND tm.work_date = ?
      WHERE e.id = ?`).bind(siteId, workDate, employeeId).first();
  }
  if (path === "/api/equipment") {
    if (payload.action === "save-timesheet-mark") {
      const siteId = positiveInteger(payload.siteId);
      const equipmentId = positiveInteger(payload.equipmentId);
      const workDate = typeof payload.workDate === "string" ? payload.workDate : "";
      if (!siteId || !equipmentId || !workDate) return null;
      return db.prepare(`SELECT productive_hours AS "productiveHours", downtime_hours AS "downtimeHours", note, created_by AS "updatedBy"
        FROM equipment_timesheet_marks WHERE site_id = ? AND equipment_id = ? AND work_date = ?`).bind(siteId, equipmentId, workDate).first();
    }
    const entryId = positiveInteger(payload.id);
    if (!entryId) return null;
    return db.prepare(`SELECT ee.id, ee.work_date AS "workDate", ee.hours, ee.note,
      eu.equipment_type AS "equipmentType", eu.brand, eu.model, eu.registration_number AS "registrationNumber"
      FROM equipment_entries ee JOIN equipment_units eu ON eu.id = ee.equipment_id WHERE ee.id = ?`).bind(entryId).first();
  }
  if (path === "/api/data" && (!payload.action || method === "DELETE")) {
    const ids = [payload.id, ...(Array.isArray(payload.ids) ? payload.ids : []), ...(Array.isArray(payload.updates) ? payload.updates.map((row) => row && typeof row === "object" ? (row as Record<string, unknown>).id : null) : [])]
      .map(positiveInteger).filter((id): id is number => id !== null);
    if (!ids.length) return null;
    const rows = await db.prepare(`SELECT id, work_date AS "workDate", employee_name_snapshot AS "employeeName", hours, note, revision
      FROM placement_entries WHERE id = ANY(?)`).bind([...new Set(ids)]).all();
    return rows.results;
  }
  return null;
}

export async function prepareAuditEvent(request: Request): Promise<AuditDraft | null> {
  try {
    if (request.method === "GET") return null;
    const actor = await getAuthUser(request);
    if (!actor) return null;
    const url = new URL(request.url);
    const payload = await requestPayload(request);
    if (request.method === "DELETE") {
      for (const [key, value] of url.searchParams) if (!(key in payload)) payload[key] = value;
    }
    const description = actionDescription(url.pathname, request.method, payload, url);
    if (!description) return null;
    const siteId = firstSiteId(payload, url);
    const site = siteId ? await getDatabase().prepare("SELECT name FROM sites WHERE id = ?").bind(siteId).first<{ name: string }>() : null;
    return {
      actor,
      ...description,
      siteId,
      siteName: site?.name ?? "",
      beforeData: safeAuditValue(await previousState(url.pathname, request.method, payload)),
      requestedData: safeAuditValue(payload),
      requestPath: url.pathname,
    };
  } catch (error) {
    console.error("Audit preparation failed", error);
    return null;
  }
}

async function finishAuditEvent(draft: AuditDraft, response: Response) {
  await ensureAuditSchema();
  let responseData: unknown = null;
  try { responseData = await response.clone().json(); } catch { responseData = null; }
  const afterData = safeAuditValue({ requested: draft.requestedData, result: responseData });
  await getDatabase().prepare(`INSERT INTO audit_events
    (actor_user_id, actor_name, actor_role, category, action_key, entity_type, entity_id, site_id, site_name, summary, before_data, after_data, request_path)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?::jsonb, ?)`)
    .bind(draft.actor.id, draft.actor.fullName, draft.actor.role, draft.category, draft.actionKey, draft.entityType, draft.entityId,
      draft.siteId, draft.siteName, draft.summary, draft.beforeData === undefined ? null : JSON.stringify(draft.beforeData), JSON.stringify(afterData), draft.requestPath).run();
}

export async function withAuditTrail(request: Request, handler: (request: Request) => Promise<Response>) {
  const auditRequest = request.clone();
  const draft = await prepareAuditEvent(auditRequest);
  const response = await handler(request);
  if (draft && response.ok) {
    try { await finishAuditEvent(draft, response); }
    catch (error) { console.error("Audit write failed", error); }
  }
  return response;
}
