import { Pool, type PoolClient, type QueryResult, type QueryResultRow, types } from "pg";

export type DatabaseResult<T = Record<string, unknown>> = {
  results: T[];
  success: true;
  meta: {
    changes: number;
    last_row_id: number | null;
  };
};

type Queryable = Pool | PoolClient;

// PostgreSQL returns bigint values such as COUNT(*) and SUM(integer) as strings
// by default. All identifiers in this application fit safely inside a JS number.
types.setTypeParser(20, (value) => Number(value));
types.setTypeParser(1114, (value) => value);
types.setTypeParser(1184, (value) => value);

function replacePlaceholders(sql: string) {
  let output = "";
  let parameter = 0;
  let singleQuoted = false;
  let doubleQuoted = false;

  for (let index = 0; index < sql.length; index += 1) {
    const character = sql[index];
    const next = sql[index + 1];
    if (character === "'" && !doubleQuoted) {
      output += character;
      if (singleQuoted && next === "'") {
        output += next;
        index += 1;
      } else {
        singleQuoted = !singleQuoted;
      }
      continue;
    }
    if (character === '"' && !singleQuoted) {
      output += character;
      if (doubleQuoted && next === '"') {
        output += next;
        index += 1;
      } else {
        doubleQuoted = !doubleQuoted;
      }
      continue;
    }
    if (character === "?" && !singleQuoted && !doubleQuoted) {
      parameter += 1;
      output += `$${parameter}`;
      continue;
    }
    output += character;
  }
  return output;
}

function translateSql(source: string) {
  const ignoreConflict = /^\s*INSERT\s+OR\s+IGNORE\s+INTO\b/i.test(source);
  let sql = source
    .replace(/^\s*INSERT\s+OR\s+IGNORE\s+INTO\b/i, (match) => match.replace(/OR\s+IGNORE\s+/i, ""))
    .replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\b(expires_at|used_at|created_at|revoked_at|invited_at|activated_at|updated_at|deleted_at)\s+TEXT\b/gi, "$1 TIMESTAMPTZ")
    .replace(/DATETIME\(\s*'now'\s*,\s*\?\s*\)/gi, "(CURRENT_TIMESTAMP + (?::interval))")
    .replace(/DATETIME\(\s*'now'\s*,\s*'([^']+)'\s*\)/gi, "(CURRENT_TIMESTAMP + INTERVAL '$1')")
    .replace(/DATE\(\s*'now'\s*\)/gi, "CURRENT_DATE")
    .replace(/GROUP_CONCAT\(([^,()]+),\s*'([^']*)'\)/gi, "STRING_AGG($1, '$2')")
    .replace(/([A-Za-z_][A-Za-z0-9_.]*)\s+NOT\s+GLOB\s+'\*\[\^0-9\]\*'/gi, "$1 !~ '[^0-9]'")
    .replace(/\bAS\s+([a-z_][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)\b/g, 'AS "$1"');

  if (ignoreConflict && !/\bON\s+CONFLICT\b/i.test(sql)) sql = `${sql.trimEnd()} ON CONFLICT DO NOTHING`;
  return replacePlaceholders(sql);
}

function tableInfoQuery(tableName: string) {
  return {
    text: `SELECT column_name AS name
      FROM information_schema.columns
      WHERE table_schema = current_schema() AND table_name = $1
      ORDER BY ordinal_position`,
    values: [tableName],
  };
}

function queryFor(source: string, values: unknown[], returnInsertedId: boolean) {
  const pragmaMatch = source.trim().match(/^PRAGMA\s+table_info\(([^)]+)\)$/i);
  if (pragmaMatch) return tableInfoQuery(pragmaMatch[1].replaceAll(/["'`]/g, "").trim());
  if (/^PRAGMA\s+optimize$/i.test(source.trim())) return null;

  let text = translateSql(source);
  if (returnInsertedId && /^\s*INSERT\s+INTO\b/i.test(text) && !/\bRETURNING\b/i.test(text)) {
    text = `${text.trimEnd()} RETURNING id`;
  }
  return { text, values };
}

export class PostgresStatement {
  private readonly values: unknown[];

  constructor(
    private readonly database: PostgresDatabase,
    private readonly source: string,
    values: unknown[] = [],
  ) {
    this.values = values;
  }

  bind(...values: unknown[]) {
    return new PostgresStatement(this.database, this.source, values);
  }

  async all<T = Record<string, unknown>>() {
    return this.database.execute<T>(this.source, this.values, false);
  }

  async first<T = Record<string, unknown>>() {
    const result = await this.database.execute<T>(this.source, this.values, false);
    return result.results[0] ?? null;
  }

  async run() {
    return this.database.execute(this.source, this.values, true);
  }

  executeWith(queryable: Queryable) {
    return this.database.execute(this.source, this.values, true, queryable);
  }
}

export class PostgresDatabase {
  constructor(private readonly pool: Pool) {}

  private async connect() {
    let lastError: unknown;
    for (let attempt = 0; attempt < 2; attempt += 1) {
      let client: PoolClient | undefined;
      try {
        client = await this.pool.connect();
        return client;
      } catch (error) {
        lastError = error;
        client?.release(true);
      }
    }
    throw lastError;
  }

  prepare(source: string) {
    return new PostgresStatement(this, source);
  }

  async execute<T = Record<string, unknown>>(
    source: string,
    values: unknown[],
    returnInsertedId: boolean,
    queryable: Queryable = this.pool,
  ): Promise<DatabaseResult<T>> {
    const translated = queryFor(source, values, returnInsertedId);
    if (!translated) return { results: [], success: true, meta: { changes: 0, last_row_id: null } };
    const client = queryable === this.pool ? await this.connect() : null;
    try {
      const result = await (client ?? queryable).query(translated.text, translated.values) as QueryResult<QueryResultRow>;
      const insertedId = result.rows[0] && "id" in result.rows[0] ? Number(result.rows[0].id) : null;
      return {
        results: result.rows as T[],
        success: true,
        meta: { changes: result.rowCount ?? 0, last_row_id: Number.isFinite(insertedId) ? insertedId : null },
      };
    } finally {
      client?.release();
    }
  }

  async batch(statements: PostgresStatement[]) {
    const client = await this.connect();
    try {
      await client.query("BEGIN");
      const results = [];
      for (const statement of statements) results.push(await statement.executeWith(client));
      await client.query("COMMIT");
      return results;
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }
  }

  async readBatch(statements: PostgresStatement[]) {
    return Promise.all(statements.map((statement) => statement.all()));
  }
}

type DatabaseGlobals = typeof globalThis & {
  personnelDatabase?: PostgresDatabase;
  personnelPool?: Pool;
};

function sslConfiguration() {
  const mode = process.env.DATABASE_SSL ?? (process.env.NODE_ENV === "production" ? "verify-full" : "disable");
  if (mode === "disable") return undefined;
  const certificate = process.env.DATABASE_CA_CERT?.replaceAll("\\n", "\n");
  if (mode === "verify-full" && !certificate) {
    throw new Error("DATABASE_CA_CERT is required when DATABASE_SSL=verify-full.");
  }
  return certificate ? { ca: certificate, rejectUnauthorized: true } : { rejectUnauthorized: false };
}

export function getDatabase() {
  const globals = globalThis as DatabaseGlobals;
  if (globals.personnelDatabase) return globals.personnelDatabase;
  const connectionString = process.env.DATABASE_URL;
  const host = process.env.PGHOST;
  if (!connectionString && !host) {
    throw new Error("DATABASE_URL or PGHOST is not configured.");
  }
  const pool = new Pool({
    ...(connectionString
      ? { connectionString }
      : {
          host,
          port: Number(process.env.PGPORT ?? 5432),
          user: process.env.PGUSER,
          password: process.env.PGPASSWORD,
          database: process.env.PGDATABASE ?? "personnel",
        }),
    ssl: sslConfiguration(),
    max: Number(process.env.DATABASE_POOL_SIZE ?? 5),
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 10_000,
    keepAlive: true,
  });
  pool.on("error", (error) => console.warn("PostgreSQL idle client error:", error.message));
  globals.personnelPool = pool;
  globals.personnelDatabase = new PostgresDatabase(pool);
  return globals.personnelDatabase;
}
